version: "3.8"

services:
  movie-platform:
    image: movie-platform-next-image
    container_name: docker-next
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules

# RECOMMENDED INTERACTION
# START:  docker-compose up
# PAUSE:  docker-compose stop
# RESUME: docker-compose start
# CLEAN:  docker-compose down --volumes